### ISSUE TITLE
Demonstrate 

### ISSUE THREAD

**Issue by ProgrammerIn-wonderland** [immortal-miku/talk-with-me#6]
Hi forum player

**Comment by ProgrammerIn-wonderland** [comment]
Send a message

**Comment by ForumPlayer** [comment]
Segmentation fault (Core dumped)

**Comment by ProgrammerIn-wonderland** [comment]
Very cool

**Comment by ProgrammerIn-wonderland** [comment]
Look ma! No refresh!

**Comment by ForumPlayer** [comment]
well, took some secs to login since i had to find the 2fa app

**Comment by ProgrammerIn-wonderland** [comment]
Understandable

**Comment by ForumPlayer** [comment]
since i rarelly need it, i removed from my home screen

**Comment by ProgrammerIn-wonderland** [comment]
2fa is a necessary evil

**Comment by ProgrammerIn-wonderland** [comment]
But yeah isn't this cool?

**Comment by ForumPlayer** [comment]
indeed it is

**Comment by ProgrammerIn-wonderland** [comment]
Idk when GitHub made issues realtime, and I don't see anywhere online stating it

**Comment by ProgrammerIn-wonderland** [comment]
But they did

**Comment by ForumPlayer** [comment]
do you know if the "Discussions" are also realtime?

**Comment by ProgrammerIn-wonderland** [comment]
Wanna try?

**Comment by ProgrammerIn-wonderland** [comment]
Let me open a thread

**Comment by ProgrammerIn-wonderland** [comment]
I opened one and pinged you in it
